# Generated by Django 2.2.7 on 2020-01-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cciApp', '0002_course_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='blog/')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
